# docker-compose.yml

version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql-course-authentication
    environment:
      MYSQL_DATABASE: db-user
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
      - db-user_data:/var/lib/mysql

volumes:
  db-user_data:
